### Audio
input_type: "raw"
quantize_channels: 65536
sample_rate : 16000 # hz
fft_frame_size : 50.0 # ms
fft_hop_size : 12.5 # ms
num_mels : 80 # filters
min_freq : 125 # hz
max_freq : 7600 # hz
floor_freq : 0.01 # reference freq for power to db conversion
n_mfcc: 13
x  : 512


### Model
layers: 10
dilation_channels: 128
stacks: 2
residual_channels: 128
skip_channels: 64
end_channels: 64
classes: 256
output_length: 1
kernel_size: 2
cin_channels: -1 # should be equal to num_mels if conditioned
bias: True


### Optimizer
initial_learning_rate: 0.001
weight_decay: 0

### Training
split: 0.8 # proportion of train set
num_epochs: 25
batch_size: 1
log_every_n_samples: 1
resume: False # resume training
num_workers: 1 # cores used for data loading
seed: 250 # random seed
valid_size: 0.1

### Audio generation
sample_size: 2000



