### Audio
input_type: "raw"
quantize_channels: 65536
sample_rate : 16000 # hz
fft_frame_size : 50.0 # ms
fft_hop_size : 12.5 # ms
num_mels : 80 # filters
min_freq : 125 # hz
max_freq : 7600 # hz
floor_freq : 0.01 # reference freq for power to db conversion
n_mfcc: 13
hop_length : 512


### Model
layers: 4
dilation_channels: 4
stacks: 1
residual_channels: 4
skip_channels: 4
end_channels: 4
classes: 256
output_length: 1
kernel_size: 2
cin_channels: 80 # should be equal to num_mels=80 if conditioning
bias: False


### Optimizer
initial_learning_rate: 0.001
weight_decay: 0
adam_beta1: 0.9
adam_beta2: 0.999
adam_eps: 0.00000001
amsgrad: False

### Training
device: 'cpu'
split: 0.7 # proportion of train set
num_epochs: 1
batch_size: 1
log_every_n_samples: 1
resume: False # resume training
num_workers: 1 # cores used for data loading
seed: 250 # random seed
valid_size: 0.1
max_time_steps: 8000

### Audio generation
sample_size: 2000

